spring:
  datasource:
    username: postgres
    password: Shoxruh0912
    url: jdbc:postgresql://localhost:5432/affiliation_shluz
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB
      enabled: true
      file-size-threshold: 2KB
springdoc:
  swagger-ui:
    path: /swagger-ui
    groups-order: asc
    operations-sorter: alpha
    try-it-out-enabled: true
    tags-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /api/doc

justice:
  request:
    json-rpc: 2.0
    method: 12341234
  api:
    key: 12341234
    base-url: 12342134

etp:
  rabbit:
    dev:
      username: username
      password: password
      port: 5672
      host: dev-rabbit.mf.uz
    prod:
      username: username
      password: password
      port: 5672
      host: prod-rabbit.mf.uz
    consumer-queue-name: ant_test
    publisher-exchange-name: common
    publisher-routing-key-xt-xarid: xt.request
    publisher-routing-key-uz-ex: xt.request

request:
  id:
    file:
      path: /home/shoxruh/requestId.dat
server:
  port: ${APP_PORT:7000}